---
- name: Test if the developer has everything setup.
  hosts: all
  tasks:

    - name: Test retrieving values from Vault
      set_fact:
        jenkins_account: "{{ lookup('community.hashi_vault.hashi_vault', 'dev_secret/data/accounts', token=hashicorp_vault_token, url=hashicorp_vault_addr).jenkins_account | from_yaml }}"

    - name: Display value from Vault
      debug:
        msg: "Retrieved value: {{ jenkins_account.username }}"

    - name: Test sudo on nodes
      become: yes
      ansible.builtin.command:
        cmd: whoami
      register: whoamiOutput
      failed_when: whoamiOutput.stdout != 'root'

    - name: Whoami output as sudo
      debug:
        msg: "whoami: {{ whoamiOutput.stdout }}"
